
networks:
  cicd_network:
    driver: bridge

volumes:
  gitea_data:


services:
  gitea:
    image: gitea/gitea:1.26.0
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=sqlite3
    networks:
      - cicd_network
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "222:22"

  code-server:
    image: linuxserver/code-server:4.116.0-ls333
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTH=none
    volumes:
      - ./workspace:/config/workspace
      - ./ide_config/code-server-init.sh:/custom-cont-init.d/init-git.sh
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - cicd_network

  jenkins:
    build: ./jenkins_config
    container_name: jenkins
    user: root
    restart: unless-stopped
    networks:
      - cicd_network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:1.29.8
    container_name: nginx
    restart: always
    networks:
      - cicd_network
    ports:
      - "80:80"
