pipeline {
    agent any

    triggers {
        pollSCM('* * * * *')
    }

    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Building demo-website:latest'
                    sh 'docker build -t demo-website:latest .'
                }
            }
        }
        stage('Clean') {
            steps {
                script {
                    echo 'Cleaning up existing nginx container'
                    sh 'docker stop nginx || true'
                    sh 'docker rm nginx || true'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying demo-website:latest'
                    sh 'docker run -d --name nginx -p 80:80 demo-website:latest'
                }
            }
        }
    }
}
